os: linux
dist: xenial
language: java
install: true
jdk: openjdk11
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo sed -i 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  # install Gradle 6.2
  # - psql -c 'CREATE DATABASE groundserver' -U postgres
  # - psql -c 'CREATE DATABASE groundservertest' -U postgres
  # - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - wget https://services.gradle.org/distributions/gradle-6.2-bin.zip
  - unzip gradle-6.2-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.2
  - export PATH=$GRADLE_HOME/bin:$PATH
  # create the databases
  - POSTGRES_MULTIPLE_DATABASES=groundserver,groundservertest ./pg-docker-script/create-multiple-databases.sh
  # since we have no db container, need to alias localhost to db so it can find the db
  - sudo sed -i '/127.0.0.1/ s/$/db/' /etc/hosts
script:
  - java -jar checkstyle/checkstyle-8.24-all.jar -c checkstyle/google_checks.xml src/main
  - gradle check --info
addons:
  postgresql: "11.2"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
