version: '3.3'

services:
    db:
        image: postgres:latest
        expose:
            - 5432
        container_name: postgres_db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./pg-docker-script:/docker-entrypoint-initdb.d
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_MULTIPLE_DATABASES: groundserver,groundservertest
            POSTGRES_PASSWORD: admin
  
    groundserver:
        image: groundserver:latest
        build:
            context: .
        working_dir: "/home/gs-backend"
        depends_on:
            - db
        volumes:
            - ./:/home/gs-backend
        expose:
            - 9000
        ports:
            - 9000:9000
        restart: always


