version: '3.3'

services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        expose:
            - 5432
        container_name: postgres_db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: groundserver
            POSTGRES_PASSWORD: admin
  
    groundserver:
        image: groundserver:latest
        depends_on:
            - db
        expose:
            - 9000
        ports:
            - 9000:9000
        restart: always

volumes:
    postgres-data:
